// Import the global CSS directly
import "./globals.css";
import { Inter } from "next/font/google";

import Home from './page'
import Header from '../app/src/components/Header/Header.jsx'
import QuestionCards from "./src/components/QuestionCards/QuestionCards";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Metadata */}
      </head>
      <body className={inter.className}>
        <div className='wrapper'>
          <Header/>
            <main>{children}</main>
          </div>
      </body>
    </html>
  );
}
